### ISSUE TITLE
BUG: Structure view isn't sorted at all

### ISSUE THREAD

**Issue by chuacw** [pontem-network/intellij-move#115]
Structure View isn't sorted at all.

I'm using IntelliJ 2023.2, and the Move plugin released on Jul 28.

![image](https://github.com/pontem-network/intellij-move/assets/1757930/448df942-fcba-4184-8db5-13fbb8a56055)

**Comment by mkurnikov** [comment]
![image](https://github.com/pontem-network/intellij-move/assets/2341827/0b4010ec-f17e-4a2d-a52f-255dd03a82cf)

I use the old UI myself, so I think I missed testing on the new one, or it might be accessible from some other menu, not the toolbar. Could you check it on the old UI? 

And also please double-check filters/sorters support for Structure View with some known plugin, for example Kotlin, it has all kinds of filters/sorters in that tool window.

**Comment by chuacw** [comment]
When I clicked the ↓AZ, it worked, but why doesn't it group structures together, and show functions separately?

**Comment by mkurnikov** [comment]
I've just looked at other implementations, and haven't found the examples of that kind of sorter, so I assumed nobody really needs it. 

But you've right, it's really useful to be able to sort according to item types, I'm going to add it in the next patch release.  I think it should be a separate sorter though, like 1) sort by item type, 2) sort by name, and allow them to be stackable. 

Created the issue here https://github.com/pontem-network/intellij-move/issues/116

**Comment by chuacw** [comment]
Thanks for quickly filing an issue for this.

I hope the new functionality groups item types first, then sorts the items within alphabetically.

**Comment by chuacw** [comment]
I'm closing this since it's already sorted, just not grouped by types.
